# Generated by Django 4.0.4 on 2022-04-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('ALIVE', 'Alive'), ('DEAD', 'Dead'), ('UNKNOWN', 'unknown')], default='UNKNOWN', max_length=10)),
                ('species', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('ALIVE', 'Alive'), ('DEAD', 'Dead'), ('UNKNOWN', 'unknown')], default='UNKNOWN', max_length=10)),
                ('origin', models.JSONField(null=True)),
                ('location', models.JSONField(null=True)),
                ('image', models.TextField()),
                ('episode', models.JSONField()),
                ('url', models.TextField()),
                ('created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.BooleanField(choices=[('IDENTICAL', True), ('NONIDENTICAL', False)], default='NONIDENTICAL')),
                ('characters', models.JSONField()),
            ],
        ),
    ]
