# Generated by Django 4.0.4 on 2022-04-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charachters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.CharField(choices=[('ALIVE', '"Alive"'), ('DEAD', 'Dead'), ('UNKNOWN', 'unknown')], default='UNKNOWN', max_length=10),
        ),
        migrations.AlterField(
            model_name='character',
            name='status',
            field=models.CharField(choices=[('ALIVE', '"Alive"'), ('DEAD', 'Dead'), ('UNKNOWN', 'unknown')], default='UNKNOWN', max_length=10),
        ),
        migrations.AlterField(
            model_name='character',
            name='type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
